<?php

namespace Database\Seeders;

use App\Models\Netmask;
use Illuminate\Database\Seeder;

class NetmaksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Netmask::create([
            'bits'=>1,
            'mask'=>'128.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>2,
            'mask'=>'192.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>3,
            'mask'=>'224.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>4,
            'mask'=>'240.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>5,
            'mask'=>'248.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>6,
            'mask'=>'252.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>7,
            'mask'=>'254.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>8,
            'mask'=>'255.0.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>9,
            'mask'=>'255.128.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>10,
            'mask'=>'255.192.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>11,
            'mask'=>'255.224.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>12,
            'mask'=>'255.240.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>13,
            'mask'=>'255.248.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>14,
            'mask'=>'255.252.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>15,
            'mask'=>'255.254.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>16,
            'mask'=>'255.255.0.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>17,
            'mask'=>'255.255.128.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>18,
            'mask'=>'255.255.192.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>19,
            'mask'=>'255.255.224.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>20,
            'mask'=>'255.255.240.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>21,
            'mask'=>'255.255.248.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>22,
            'mask'=>'255.255.252.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>23,
            'mask'=>'255.255.254.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>24,
            'mask'=>'255.255.255.0',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>25,
            'mask'=>'255.255.255.128',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>26,
            'mask'=>'255.255.255.192',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>27,
            'mask'=>'255.255.255.224',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>28,
            'mask'=>'255.255.255.240',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>29,
            'mask'=>'255.255.255.248',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>30,
            'mask'=>'255.255.255.252',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>31,
            'mask'=>'255.255.255.254',
            'user_id'=>1
        ]);
        Netmask::create([
            'bits'=>32,
            'mask'=>'255.255.255.255',
            'user_id'=>1
        ]);

    }
}
